Repository chocolatey-community/chocolatey-packages, pull requests merged in 2018-06, with the labels that each got.

#970 (lightscreen) Migrate package
  automatic/lightscreen/README.md
  automatic/lightscreen/legal/LICENSE.txt
  automatic/lightscreen/legal/VERIFICATION.txt
  automatic/lightscreen/lightscreen.nuspec
  automatic/lightscreen/tools/chocolateyInstall.ps1
  automatic/lightscreen/update.ps1
  icons/lightscreen.png
Labels: 3 - Done, migration

#1023 (gitextensions) Migrate package
  automatic/gitextensions/README.md
  automatic/gitextensions/gitextensions.nuspec
  automatic/gitextensions/legal/VERIFICATION.txt
  automatic/gitextensions/tools/chocolateyInstall.ps1
  automatic/gitextensions/tools/chocolateyUninstall.ps1
  automatic/gitextensions/update.ps1
Labels: migration

#1055 (docs) Updated guidelines with choco version requirement
  CONTRIBUTING.md
  README.md
Labels: Question/Discussion
