Repository chocolatey-community/chocolatey-packages, pull requests merged in 2019-09, with the labels that each got.

#1345 (protoc) Migrate Protocol Buffer
  automatic/protoc/README.md
  automatic/protoc/legal/LICENSE.txt
  automatic/protoc/legal/VERIFICATION.txt
  automatic/protoc/protoc.nuspec
  automatic/protoc/tools/chocolateyBeforeModify.ps1
  automatic/protoc/tools/chocolateyinstall.ps1
  automatic/protoc/update.ps1
Labels: 3 - Done, Requires Chocolatey User, migration

#1335 (vim) Add vim
  automatic/vim/README.md
  automatic/vim/legal/LICENSE.txt
  automatic/vim/legal/VERIFICATION.txt
  automatic/vim/tools/chocolateybeforemodify.ps1
  automatic/vim/tools/chocolateyinstall.ps1
  automatic/vim/tools/chocolateyuninstall.ps1
  automatic/vim/tools/helpers.ps1
  automatic/vim/update.ps1
  automatic/vim/vim.nuspec
  icons/vim.svg
Labels: 3 - Done, migration

#1348 (msys2) fix and tidy up installer
  automatic/msys2/tools/chocolateyinstall.ps1
  automatic/msys2/tools/helpers.ps1
Labels: 3 - Done
